Stage 1: statistics service
AleksandrTimofeev1987/java-explore-with-me pull request #1
Opened 2023-01-29 20:45 UTC by AleksandrTimofeev1987

feature: create stats server
feature: create main service draft
feature: create stats db
feature: create main db

2023-01-30 17:43 UTC, Fleaman777 requested changes

2023-01-30 17:43 UTC, Fleaman777 commented on stats-client/src/main/java/ru/practicum/client/EndpointHitClient.java
> +    public EndpointHitClient(@Value("http://localhost:9090") String serverUrl, RestTemplateBuilder builder) {
в таком ввиде @Value("http://localhost:9090") эта аннотация особо не нужна, т.к. по сути, она просечиает всегда одно значение, которое можно установить более простыми способами, 

но лучше конечно сделать так, что бы это значение подтягивалось из application.properties

аналагично в др похожих местах

2023-01-30 17:43 UTC, Fleaman777 commented on stats-server/pom.xml
> +            <version>1.5.3.Final</version>
явные версии можно было бы вынести в parent pom, 
так, у тебя будет одно место в приложении, где будут менеджиться версии зависимостей

2023-01-30 17:43 UTC, Fleaman777 commented on stats-server/src/main/java/ru/practicum/dto/ViewStats.java
> +    Long hits;
поля должны быть private

2023-01-30 18:50 UTC, AleksandrTimofeev1987 commented on stats-client/src/main/java/ru/practicum/client/EndpointHitClient.java
> +    public EndpointHitClient(@Value("http://localhost:9090") String serverUrl, RestTemplateBuilder builder) {
У меня из application.properties не подтягивалось и из-за этого основной сервис не запускался. Но теперь я догадался, что stats-client у меня является зависимостью ewm-service (основного сервиса) и именно в основном сервисе и нужно переменную окружения задавать. Сделано)

2023-01-30 19:01 UTC, AleksandrTimofeev1987 commented on stats-server/pom.xml
> +            <version>1.5.3.Final</version>
А если неявные версии, но зависимость используется в нескольких модулях, имеет ли смысл в parent pom запихивать такие зависимости или лучше в каждый модуль их добавлять лучше? Как пример - Lombok, Postgresql и т.п.

2023-01-31 08:55 UTC, Fleaman777 approved these changes

2023-02-01 15:40 UTC, Fleaman777 commented on stats-server/pom.xml
> +            <version>1.5.3.Final</version>
ну да, тут смысл как у Lombok, Postgresql, и пр.
что бы в разных модулях версии зависимостей были одинаковые и не было конфликтов, лучше иметь одну точку, где будут заданы версии, т.е. в parent pom. Можно посмотреть в сторону <properties> и там прописывать версии

2023-02-14 20:06 UTC, merged