Second Stage
AleksandrTimofeev1987/java-explore-with-me pull request #2
Opened 2023-02-06 19:06 UTC by AleksandrTimofeev1987

2023-02-08 06:41 UTC, Fleaman777 requested changes

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/category/controller/CategoryControllerAdmin.java
> +public class CategoryControllerAdmin {
по общепризнанной практике, в названии контроллера слово Controller должно быть в конце

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceAdmin.java
> +public interface CategoryServiceAdmin {
с названиям сервисов анаоагичо названиям контроллеров, Servive в конце названия

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/controller/EventControllerAdmin.java
> +                                 @Positive @RequestParam(defaultValue = "10") Integer size) {
понимаю, что это было требование ТЗ, 
но лучше конечно стараться не делать очень много параметров в запросе, а тем более списков, т.к. большое количество параметров ухудшает построение взаимодействия между сервисами
 как альтерантива, исользовать боди в пост запросе

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceAdminImpl.java
> +        Event savedEvent = eventRepository.findById(eventId).orElseThrow(() -> new NotFoundException(String.format("Event with id=%d is not found", eventId)));
хороший ход с просечиванием параметров в месседж, а не просто конкатенацией строк

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServiceAdminImpl.java
> +                break;
логику внутри каждого блока case, можно было бы вынести в отдельный вспомогательный метод, тем самым немного улучшив восприятие кода

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServicePrivateImpl.java
> +            throw new ConflictException("Event title is duplicate.");
не обязательно к исполнению, но просто как на заметку, 

для еррор месседжей можно использовать, так скажем, хранилище этих сообщение в формате ключ значение, 
messages.properties - файл, в котором будет это все хранится 

позволяет уменьшить дублирование одинаковых месседжей, 
так же будет одно место, где они хранятся, что удобно для управления-изменения этих меседжей

более подробно можно посмотреть здесь
https://www.baeldung.com/spring-custom-validation-message-source

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServicePrivateImpl.java
> +        RequestStatusUpdateResponse result = new RequestStatusUpdateResponse(new ArrayList<>(), new ArrayList<>());
возможно для удобства, можно было бы сразу в классе RequestStatusUpdateResponse сразу проинициализировать confirmedRequests; rejectedRequests; как пустые списки

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServicePrivateImpl.java
> +    }
попробуй этот метод немного разбить, какую-нибудь логику вынести в отдельный приватный метод, 
когда в методе друг за другом идут несолько блоков if-else, foreach, try-catch чтение и понимаение кода затрудняется

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServicePublicImpl.java
> +        foundEvents = foundEvents
я думаю, можно сразу сделать 
List<Event> foundEvents = repository.findAll(expression, page).getContent().stream()....

минуя момент с переприсваиванием foundEvents = foundEvents.stream()....

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/exception/handler/ErrorHandler.java
> +        return buildResponseEntity(new ApiError(HttpStatus.BAD_REQUEST, "Incorrect request", e.getFieldError().getDefaultMessage(), LocalDateTime.now()));
а чем "Bad request" отличается от "Incorrect request",

если принципиальной рахницы нет, можно привести к одному ввиду

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/request/entity/Request.java
> +    @ManyToOne(fetch = FetchType.LAZY, optional = false)
а почему FetchType не EAGER ? 
обычно для @ManyToOne это оптимальный подход

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +}
хорошие методы verify...., все понятно и выглдяит отлично

2023-02-08 06:41 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServicePublicImpl.java
> +        return foundEvents
понимаю, для чего приходится дважды вызывать стрим и собирать в листы, 
но так ли нам нужен этот лог, в потенциальный ущерб производительности 🤔

как вариант, логировать после получения найденный ивентов (тогда пред. комментарий не применять)
List foundEvents = repository.findAll(expression, page).getContent();
log(....size...)

а потом уже смело полностью выполнять стрим, без его разделения на лог

2023-02-08 08:31 UTC, AleksandrTimofeev1987 commented on ewm-service/src/main/java/ru/practicum/event/controller/EventControllerAdmin.java
> +                                 @Positive @RequestParam(defaultValue = "10") Integer size) {
Принято на будущее. Спасибо.

2023-02-09 08:27 UTC, AleksandrTimofeev1987 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServicePublicImpl.java
> +        return foundEvents
Да, согласен. Загнал все в один стрим и собрал итоговый лист, сохранив его в локальную переменную, потом лог, потом return локальной переменной.

2023-02-09 10:09 UTC, AleksandrTimofeev1987 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServicePrivateImpl.java
> +            throw new ConflictException("Event title is duplicate.");
Спасибо. Очень классная вещь. С валидацией все легко получилось, но вот с исключениями пришлось повозиться. В итоге единственный вразумительный способ, который нашел в интернете: инжектить MessageSource в классы сервисов и добывать сообщение оттуда. Зато это дает возможность параметризированные сообщения использовать. Возможно есть более простой способ? Подскажи на будущее.
По логам не стал делать хранилище сообщений, так как там повторяющихся сообщений нет.

2023-02-09 19:23 UTC, Fleaman777 approved these changes

2023-02-09 19:23 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/compilation/dto/CompilationCreate.java
> +    @NotBlank(message = "{title.compilation.not_blank}")
здорово, что решил не откладывать в долгий ящик, а сразу применить на практике)

2023-02-09 19:23 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/service/EventAdminServiceImpl.java
>          switch (eventDto.getStateAction()) {
есть такой паттерн проектирования - стратегия, 
его в принципе неплохо можно применить  к подобным вещам, типа switch case, 

за корректность синтаксиса не отвечаю, писал на коленке) 
но его имплементация примерно выглялит так, 

создается поле класса EventAdminServiceImpl 
Map<StateAction, Consumer<Event>> settingEventStatusMap = Map.of(
PUBLISH_EVENT, event -> setEventStatusPublished(event),
REJECT_EVENT, event -> setEventStatusCanceled(event)
);

а в самом методе formEventForUpdate сделать вот так

settingEventStatusMap.get(eventDto.getStateAction()).accept(event);

получается покомпактней и побыстрей
да, возможно, на 1й взгляд логика не очевидна по сравнению с классическим switch-case, но с опытом такой подход будет читаться быстро)

а так, в новой джаве есть отлично подходящий под подобные действия, улучшенный switch

2023-02-10 08:01 UTC, AleksandrTimofeev1987 commented on ewm-service/src/main/java/ru/practicum/event/service/EventAdminServiceImpl.java
>          switch (eventDto.getStateAction()) {
Спасибо за подсказку. Почитал, изучил и применил.)

2023-02-12 20:36 UTC, Fleaman777 commented on ewm-service/src/main/java/ru/practicum/event/service/EventServicePrivateImpl.java
> +            throw new ConflictException("Event title is duplicate.");
честно говоря, сходу в голову ничего дельного не приходит, 
но мне почему-то казалось, что оно как-то должно из коробки работать, 

если найдется какой-нибудь туториал, скину)

2023-02-14 20:07 UTC, closed without merging